[package]
name = "psychowl_native"
version = "0.1.0"
description = "Ruby bindings for the psychowl crate"
publish = false
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
psychowl.workspace = true
magnus.workspace = true
rayon.workspace = true
